[package]
name = "slippy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
derive_more = "0.99.17"
approx = "0.5.1"
rand_distr = "0.4.3"
rand = "0.8.5"